#!/usr/bin/env python3
"""routeviz: draw a routing table (``netstat -rn`` output) as a graph.

Input is any ``netstat -rn`` text: macOS/BSD (``Destination Gateway Flags Netif``),
Linux (``Kernel IP routing table`` with Genmask, ``Kernel IPv6 routing table``)
or Windows (``Network Destination Netmask Gateway Interface Metric``). Nothing is
tied to this machine; ``--live`` merely runs ``netstat -rn`` for you.

    python3 src/route-graph/cli/routeviz.py routes.txt                # -> routes.html
    netstat -rn | python3 src/route-graph/cli/routeviz.py -o out.html
    python3 src/route-graph/cli/routeviz.py --live --open             # this machine, open in browser
    python3 src/route-graph/cli/routeviz.py routes.txt -f text        # tree in the terminal
    python3 src/route-graph/cli/routeviz.py routes.txt --to 8.8.8.8   # longest-prefix match
    python3 src/route-graph/cli/routeviz.py routes.txt -f dot | dot -Tpng -o routes.png

The graph is a tree read left to right, the way a packet leaves the host:

    host -> interface -> connected prefix -> next hop / neighbor -> remote prefix

* An interface owns the prefixes it is directly attached to (no ``G`` flag).
* Hosts on those links (ARP/NDP cache entries, ``H`` routes) hang under the
  prefix that contains them; a next-hop router is such a neighbor too.
* Routes with the ``G`` flag hang under the router that forwards them; the
  default route (``/0``) is the shortest prefix and catches everything else.

Outputs: ``html`` (interactive page, default), ``svg`` (static), ``text`` (tree),
``dot`` (Graphviz), ``json`` (the graph model). Stdlib only, Python 3.9+.
"""

import argparse
import datetime as dt
import html
import ipaddress
import json
import os
import pathlib
import re
import socket
import subprocess
import sys

TEMPLATE = pathlib.Path(__file__).resolve().parent / "routeviz_template.html"

# --------------------------------------------------------------------------- flags

# macOS / FreeBSD netstat(1) flag letters (route(4) RTF_*).
BSD_FLAGS = {
    "U": ("RTF_UP", "route is usable"),
    "G": ("RTF_GATEWAY", "destination needs forwarding by an intermediary (a next hop)"),
    "H": ("RTF_HOST", "host entry (a single address, not a network)"),
    "S": ("RTF_STATIC", "added manually or by DHCP, not learned from the link"),
    "C": ("RTF_CLONING", "generates new host routes on use (per-neighbor ARP/NDP entries)"),
    "c": ("RTF_PRCLONING", "protocol-specified cloning"),
    "W": ("RTF_WASCLONED", "was generated by a cloning route (an ARP/NDP cache entry)"),
    "L": ("RTF_LLINFO", "holds a link-layer (MAC) address for the destination"),
    "D": ("RTF_DYNAMIC", "created dynamically by an ICMP redirect"),
    "M": ("RTF_MODIFIED", "modified dynamically by an ICMP redirect"),
    "R": ("RTF_REJECT", "host or net unreachable (packets are rejected)"),
    "B": ("RTF_BLACKHOLE", "packets are silently discarded"),
    "b": ("RTF_BROADCAST", "destination is a broadcast address"),
    "m": ("RTF_MULTICAST", "destination is a multicast address"),
    "I": ("RTF_IFSCOPE", "route is scoped to one interface"),
    "i": ("RTF_IFREF", "route holds a reference to its interface"),
    "r": ("RTF_ROUTER", "this host is a default router (advertised itself)"),
    "g": ("RTF_GLOBAL", "policy hint: destination is on the global Internet"),
    "X": ("RTF_XRESOLVE", "an external daemon resolves the link address"),
    "Y": ("RTF_PROXY", "proxying; cloned routes are not scoped"),
    "1": ("RTF_PROTO1", "protocol-specific flag 1"),
    "2": ("RTF_PROTO2", "protocol-specific flag 2"),
    "3": ("RTF_PROTO3", "protocol-specific flag 3"),
}

# Linux net-tools route/netstat flag letters.
LINUX_FLAGS = {
    "U": ("up", "route is usable"),
    "G": ("gateway", "destination needs forwarding by an intermediary (a next hop)"),
    "H": ("host", "host entry (a single address, not a network)"),
    "R": ("reinstate", "reinstate route for dynamic routing"),
    "D": ("dynamic", "installed by a routing daemon or an ICMP redirect"),
    "M": ("modified", "modified by a routing daemon or an ICMP redirect"),
    "A": ("addrconf", "installed by IPv6 address autoconfiguration"),
    "C": ("cache", "cache entry (a resolved neighbor)"),
    "e": ("expires", "the entry expires"),
    "n": ("nonexthop", "no next hop (delivered on the link)"),
    "!": ("reject", "reject route (packets are dropped)"),
}

IFACE_KINDS = [
    (r"^lo\d*$", "loopback (packets to this host itself)"),
    (r"^en\d+$", "Ethernet / Wi-Fi (en0 is usually Wi-Fi on a MacBook)"),
    (r"^(eth|eno|ens|enp|em)\d", "Ethernet"),
    (r"^(wlan|wlp|wlo|wl)\w*", "Wi-Fi"),
    (r"^utun\d+$", "userspace tunnel (VPN, iCloud Private Relay, Tailscale, ...)"),
    (r"^(tun|tap)\d+$", "tunnel (VPN)"),
    (r"^wg\d+$", "WireGuard tunnel"),
    (r"^ppp\d+$", "point-to-point link"),
    (r"^awdl\d+$", "Apple Wireless Direct Link (AirDrop, Sidecar)"),
    (r"^llw\d+$", "low-latency WLAN (companion to awdl)"),
    (r"^ap\d+$", "Wi-Fi access point (hotspot / Internet Sharing)"),
    (r"^bridge\d+$", "software bridge (Internet Sharing, VMs)"),
    (r"^(docker\d+|br-[0-9a-f]+)$", "Docker bridge"),
    (r"^veth", "virtual Ethernet pair (container)"),
    (r"^(vmnet|vboxnet|virbr)\d+$", "VM host-only / NAT network"),
    (r"^gif\d+$", "generic IP-in-IP tunnel"),
    (r"^stf\d+$", "6to4 tunnel"),
    (r"^anpi\d+$", "Apple debug/USB interface"),
    (r"^ipsec\d+$", "IPsec tunnel"),
]

FAMILY_MAX = {4: 32, 6: 128}


def iface_kind(name):
    for pat, desc in IFACE_KINDS:
        if re.match(pat, name):
            return desc
    return ""


def is_loopback_iface(name):
    return bool(re.match(r"^lo\d*$", name)) or name == "127.0.0.1"


# --------------------------------------------------------------------------- parsing

MAC_RE = re.compile(r"^(?:[0-9a-fA-F]{1,2}:){5}[0-9a-fA-F]{1,2}$")
LINK_RE = re.compile(r"^link#(\d+)$")


class ParseError(Exception):
    pass


def split_scope(text):
    """'fe80::1%en0' -> ('fe80::1', 'en0')."""
    if "%" in text:
        addr, scope = text.split("%", 1)
        return addr, scope
    return text, ""


def parse_ipv4_dest(text):
    """macOS/BSD abbreviations: 'default', '10/24', '127', '169.254', '224.0.0/4',
    '10.0.0.1/32', '10.0.0.5'. Returns an ip_network or None."""
    if text == "default":
        return ipaddress.ip_network("0.0.0.0/0")
    plen = None
    if "/" in text:
        text, p = text.split("/", 1)
        plen = int(p)
    octets = text.split(".")
    if not all(o.isdigit() and 0 <= int(o) <= 255 for o in octets) or len(octets) > 4:
        return None
    if plen is None:
        plen = 32 if len(octets) == 4 else 8 * len(octets)
    octets += ["0"] * (4 - len(octets))
    return ipaddress.ip_network("%s/%d" % (".".join(octets), plen), strict=False)


def parse_ipv6_dest(text):
    """'default', '::/0', 'fe80::%en0/64', 'ff01::%lo0/32', '2601:...::/64', '::1'.
    Returns (ip_network, scope) or (None, '')."""
    if text == "default":
        return ipaddress.ip_network("::/0"), ""
    plen = None
    if "/" in text:
        text, p = text.split("/", 1)
        plen = int(p)
    addr, scope = split_scope(text)
    try:
        ip = ipaddress.ip_address(addr)
    except ValueError:
        return None, ""
    if ip.version != 6:
        return None, ""
    if plen is None:
        plen = 128
    return ipaddress.ip_network("%s/%d" % (addr, plen), strict=False), scope


def parse_gateway(text, family):
    """Classify a Gateway / Next Hop cell.

    Returns dict(kind, ip, scope, link, mac) with kind in
    'ip' (a next hop or the local address), 'mac' (a resolved neighbor),
    'link' (BSD 'link#N': directly on the interface), 'none' (Linux 0.0.0.0 / ::,
    Windows On-link, or empty)."""
    g = {"kind": "none", "ip": "", "scope": "", "link": "", "mac": "", "raw": text}
    if not text or text in ("0.0.0.0", "::", "*", "On-link", "-"):
        return g
    m = LINK_RE.match(text)
    if m:
        g.update(kind="link", link=m.group(1))
        return g
    if MAC_RE.match(text):
        g.update(kind="mac", mac=":".join("%02x" % int(x, 16) for x in text.split(":")))
        return g
    addr, scope = split_scope(text)
    try:
        ip = ipaddress.ip_address(addr)
    except ValueError:
        return g
    g.update(kind="ip", ip=str(ip), scope=scope)
    return g


def _route(family, dest_raw, gw_raw, flags, iface, raw, expire="", extra=None, os_name="bsd"):
    return {
        "family": family, "dest": dest_raw, "gateway": gw_raw, "flags": flags or "",
        "iface": iface, "expire": expire, "raw": raw.rstrip("\n"), "extra": extra or {},
        "os": os_name,
    }


def parse_netstat(text):
    """Parse ``netstat -rn`` output from macOS/BSD, Linux or Windows.

    Returns (routes, meta). Each route is a dict; see ``classify`` for the
    fields added later."""
    routes = []
    meta = {"os": None, "sections": []}
    lines = text.splitlines()
    family = None
    columns = None
    layout = None  # 'bsd' | 'linux4' | 'linux6' | 'win4' | 'win6'
    for line in lines:
        s = line.strip()
        if not s:
            continue
        low = s.lower()
        # ---- section and header detection
        if low in ("internet:", "internet6:"):
            family = 6 if "6" in low else 4
            meta["sections"].append(s)
            columns = None
            continue
        if low.startswith("kernel ip routing table"):
            family, layout = 4, "linux4"
            meta["os"] = meta["os"] or "linux"
            meta["sections"].append(s)
            continue
        if low.startswith("kernel ipv6 routing table"):
            family, layout = 6, "linux6"
            meta["os"] = meta["os"] or "linux"
            meta["sections"].append(s)
            continue
        if low.startswith("ipv4 route table"):
            family, layout = 4, "win4"
            meta["os"] = "windows"
            meta["sections"].append(s)
            continue
        if low.startswith("ipv6 route table"):
            family, layout = 6, "win6"
            meta["os"] = "windows"
            meta["sections"].append(s)
            continue
        if low.startswith("routing tables") or low.startswith("active routes") \
                or low.startswith("persistent routes") or low.startswith("interface list") \
                or set(s) <= set("=-"):
            continue
        if re.match(r"^(network\s+destination|destination)\b", low) or low.startswith("if ") \
                or low.startswith("if\t"):
            columns = re.split(r"\s{2,}|\t+", s)
            columns = [c.strip() for c in columns if c.strip()]
            if columns and columns[0].lower() == "destination" and len(columns) == 1:
                columns = s.split()
            # Windows IPv6 header: "If Metric Network Destination      Gateway"
            if low.startswith("if"):
                columns = ["If", "Metric", "Network Destination", "Gateway"]
                layout, family = "win6", 6
            elif columns[0].lower() == "network destination":
                columns = ["Network Destination", "Netmask", "Gateway", "Interface", "Metric"]
                layout, family = "win4", 4
            elif layout not in ("linux4", "linux6"):
                cols = s.split()
                columns = cols
                layout = "bsd"
                meta["os"] = meta["os"] or "bsd"
                if family is None:
                    family = 4
            else:
                columns = s.split()
            continue
        if columns is None:
            continue  # prose before the first header (e.g. Windows interface list)
        toks = s.split()
        try:
            if layout == "bsd":
                # Destination Gateway Flags [Refs Use] [Mtu] Netif [Expire]
                idx = {c.lower(): i for i, c in enumerate(columns)}
                need = ("destination", "gateway", "flags", "netif")
                if not all(k in idx for k in need):
                    continue
                if len(toks) <= idx["netif"]:
                    continue
                r = _route(family, toks[idx["destination"]], toks[idx["gateway"]],
                           toks[idx["flags"]], toks[idx["netif"]], line,
                           expire=toks[idx["expire"]] if "expire" in idx and len(toks) > idx["expire"] else "",
                           extra={c: toks[i] for c, i in zip(columns, range(len(toks)))
                                  if c.lower() not in need + ("expire",)},
                           os_name="bsd")
                # Some BSDs print the family by the destination, not by section.
                if family == 4 and ":" in r["dest"]:
                    r["family"] = 6
                routes.append(r)
            elif layout == "linux4":
                # Destination Gateway Genmask Flags MSS Window irtt Iface
                if len(toks) < 8:
                    continue
                dest, gw, mask, flags, iface = toks[0], toks[1], toks[2], toks[3], toks[-1]
                r = _route(4, dest, gw, flags, iface, line,
                           extra={"Genmask": mask, "Metric/MSS": toks[4], "Window": toks[5], "irtt": toks[6]},
                           os_name="linux")
                r["genmask"] = mask
                routes.append(r)
            elif layout == "linux6":
                # Destination Next Hop Flag Met Ref Use If
                if len(toks) < 7:
                    continue
                dest, gw, flags, iface = toks[0], toks[1], toks[2], toks[-1]
                routes.append(_route(6, dest, gw, flags, iface, line,
                                     extra={"Metric": toks[3], "Ref": toks[4], "Use": toks[5]},
                                     os_name="linux"))
            elif layout == "win4":
                # Network Destination  Netmask  Gateway  Interface  Metric
                if len(toks) < 5:
                    continue
                dest, mask, gw, iface, metric = toks[0], toks[1], toks[2], toks[3], toks[4]
                r = _route(4, dest, gw, "", iface, line, extra={"Metric": metric}, os_name="windows")
                r["genmask"] = mask
                routes.append(r)
            elif layout == "win6":
                # If  Metric  Network Destination  Gateway
                if len(toks) < 4:
                    continue
                ifidx, metric, dest, gw = toks[0], toks[1], toks[2], " ".join(toks[3:])
                routes.append(_route(6, dest, gw, "", "if%s" % ifidx, line,
                                     extra={"Metric": metric}, os_name="windows"))
        except (IndexError, ValueError):
            continue
    if not routes:
        raise ParseError("no routes found: is this the output of `netstat -rn`?")
    meta["os"] = meta["os"] or "bsd"
    return routes, meta


def parse_ifconfig(text):
    """Minimal ifconfig / `ip addr` reader: name -> {ether, inet:[cidr], inet6:[cidr], status, mtu}."""
    ifaces = {}
    cur = None
    for line in text.splitlines():
        m = re.match(r"^(?:\d+:\s+)?([A-Za-z][\w.\-]*?)(?:@\w+)?:\s.*?(?:mtu\s+(\d+))?", line)
        if m and not line.startswith((" ", "\t")):
            cur = ifaces.setdefault(m.group(1), {"ether": "", "inet": [], "inet6": [], "status": "", "mtu": ""})
            mm = re.search(r"mtu\s+(\d+)", line)
            if mm:
                cur["mtu"] = mm.group(1)
            continue
        if cur is None:
            continue
        s = line.strip()
        m = re.match(r"^(?:ether|link/ether)\s+([0-9a-f:]{11,17})", s, re.I)
        if m:
            cur["ether"] = m.group(1).lower()
            continue
        m = re.match(r"^inet\s+(\d+\.\d+\.\d+\.\d+)(?:/(\d+))?(?:\s+netmask\s+(0x[0-9a-f]+|\d+\.\d+\.\d+\.\d+))?", s, re.I)
        if m:
            plen = m.group(2)
            if plen is None and m.group(3):
                mask = m.group(3)
                n = int(mask, 16) if mask.startswith("0x") else int(ipaddress.ip_address(mask))
                plen = bin(n).count("1")
            cur["inet"].append("%s/%s" % (m.group(1), plen or 32))
            continue
        m = re.match(r"^inet6\s+([0-9a-f:]+)(?:%\w+)?(?:/(\d+))?(?:\s+prefixlen\s+(\d+))?", s, re.I)
        if m:
            cur["inet6"].append("%s/%s" % (m.group(1), m.group(2) or m.group(3) or 128))
            continue
        m = re.match(r"^status:\s*(\w+)", s)
        if m:
            cur["status"] = m.group(1)
    return ifaces


# --------------------------------------------------------------------------- classification

def _mask_plen(mask):
    return bin(int(ipaddress.ip_address(mask))).count("1")


def classify(routes):
    """Add net/cidr/plen/bits, gateway info, kind and tags to every route.

    kind: 'default' | 'remote' (via a next hop) | 'connected' (prefix on the link)
          | 'neighbor' (a host on the link) | 'self' (one of this host's addresses)
    """
    for r in routes:
        fam = r["family"]
        r["ok"] = False
        try:
            if fam == 4:
                if r.get("genmask"):
                    net = ipaddress.ip_network("%s/%d" % (r["dest"], _mask_plen(r["genmask"])), strict=False)
                else:
                    net = parse_ipv4_dest(r["dest"])
                scope = ""
            else:
                net, scope = parse_ipv6_dest(r["dest"])
        except ValueError:
            net = None
        if net is None:
            continue
        r["ok"] = True
        r["net"] = net
        r["cidr"] = str(net)
        r["plen"] = net.prefixlen
        r["scope"] = scope
        r["bits"] = format(int(net.network_address), "0%db" % FAMILY_MAX[fam])[:net.prefixlen]
        g = parse_gateway(r["gateway"], fam)
        r["gw"] = g
        flags = set(r["flags"])
        win = r["os"] == "windows"
        lo = is_loopback_iface(r["iface"]) or (win and net.is_loopback)
        host_sized = net.prefixlen == FAMILY_MAX[fam]
        is_host = "H" in flags or (win and host_sized)
        has_gw = "G" in flags or (win and g["kind"] == "ip")
        tags = set()
        if net.prefixlen == 0:
            kind = "default"
        elif has_gw and g["kind"] == "ip":
            kind = "remote"
        elif is_host:
            own = lo or (win and str(net.network_address) == r["iface"])
            kind = "self" if own else "neighbor"
        else:
            kind = "connected"
        if net.is_multicast or "m" in flags:
            tags.add("multicast")
        if net.is_link_local:
            tags.add("linklocal")
        if lo or net.is_loopback:
            tags.add("loopback")
        if "R" in flags and r["os"] == "bsd" or "!" in flags:
            tags.add("reject")
        if "B" in flags and r["os"] == "bsd":
            tags.add("blackhole")
        if "S" in flags and r["os"] == "bsd":
            tags.add("static")
        if "W" in flags and r["os"] == "bsd" or ("C" in flags and r["os"] == "linux"):
            tags.add("cache")
        if "r" in flags and r["os"] == "bsd":
            tags.add("router")
        if kind == "connected" and (host_sized or (fam == 4 and str(net.network_address) == "255.255.255.255")):
            tags.add("bookkeeping")
        if host_sized and net.is_loopback:
            kind = "self"
        if fam == 4 and host_sized and str(net.network_address) == "255.255.255.255":
            tags.update(("broadcast", "bookkeeping"))
        if kind == "neighbor" and r["os"] == "bsd" and g["kind"] != "mac":
            tags.add("unresolved")
        if kind == "neighbor" and r["os"] != "bsd":
            tags.add("hostroute")
        if kind == "default" and r["os"] == "bsd" and "I" in flags:
            tags.update(("scoped", "bookkeeping"))  # per-interface duplicate default (utun & co.)
        if has_gw and g["kind"] != "ip" and kind != "default":
            tags.add("odd-gateway")
        r["kind"] = kind
        r["tags"] = sorted(tags)
    return routes


def flag_glossary(routes):
    """Only the flag letters that actually occur, decoded for the right OS."""
    out = {}
    for r in routes:
        table = LINUX_FLAGS if r["os"] == "linux" else BSD_FLAGS
        for ch in r["flags"]:
            if ch in table and ch not in out:
                out[ch] = {"name": table[ch][0], "meaning": table[ch][1]}
    return out


def explain_flags(r):
    table = LINUX_FLAGS if r["os"] == "linux" else BSD_FLAGS
    return [("%s = %s" % (ch, table[ch][1])) if ch in table else ("%s = ?" % ch) for ch in r["flags"]]


# --------------------------------------------------------------------------- graph model

def _iface_sort_key(name):
    m = re.match(r"^([a-zA-Z\-]+)(\d*)", name)
    base, num = (m.group(1), m.group(2)) if m else (name, "")
    rank = 3
    if is_loopback_iface(name):
        rank = 9
    elif re.match(r"^(en|eth|eno|ens|enp|em|wlan|wlp|wlo|wl|ap|bridge)", name):
        rank = 0
    elif re.match(r"^(utun|tun|tap|wg|ppp|ipsec|gif|stf)", name):
        rank = 1
    elif re.match(r"^(docker|br-|veth|vmnet|vboxnet|virbr)", name):
        rank = 2
    elif re.match(r"^\d+\.\d+\.\d+\.\d+$", name):
        rank = 0
    return (rank, base, int(num) if num else -1, name)


def _addr_int(r):
    return int(r["net"].network_address)


def build_graph(routes, ifcfg=None, hostname="this host", source=""):
    """Turn classified routes into a tree of nodes (dicts).

    host -> iface -> connected prefix -> neighbor/next hop -> remote prefix.
    """
    ifcfg = ifcfg or {}
    nodes = {}

    def add(nid, **kw):
        n = nodes.get(nid)
        if n is None:
            n = {"id": nid, "children": [], "routes": [], "tags": [], "parent": None, "sub": "", "note": ""}
            n.update(kw)
            nodes[nid] = n
        return n

    add("host", kind="host", label=hostname, family=0, note=source)
    good = [(i, r) for i, r in enumerate(routes) if r.get("ok")]
    for name in sorted({r["iface"] for _, r in good}, key=_iface_sort_key):
        n = add("if:" + name, kind="iface", label=name, family=0, parent="host", desc=iface_kind(name), addrs=[])
        info = ifcfg.get(name)
        if info:
            n["info"] = info
            n["addrs"] = list(info["inet"]) + list(info["inet6"])

    def merge_tags(n, r):
        for t in r["tags"]:
            if t not in n["tags"]:
                n["tags"].append(t)

    # 1. connected prefixes, neighbors and own addresses
    for i, r in good:
        fam, iface = r["family"], r["iface"]
        if r["kind"] == "connected":
            n = add("net:%d:%s:%s" % (fam, iface, r["cidr"]), kind="net", label=r["cidr"], family=fam,
                    parent="if:" + iface, addr=str(r["net"].network_address), plen=r["plen"], bits=r["bits"])
        elif r["kind"] in ("neighbor", "self"):
            addr = str(r["net"].network_address)
            n = add("%s:%d:%s:%s" % ("nb" if r["kind"] == "neighbor" else "self", fam, iface, addr),
                    kind=r["kind"], label=addr, family=fam, addr=addr, plen=r["plen"], bits=r["bits"])
            if r["gw"]["kind"] == "mac":
                n["mac"] = r["gw"]["mac"]
            if r["expire"] and r["expire"] not in ("!", "-"):
                n["expire"] = r["expire"]
            if r["scope"]:
                n["scope"] = r["scope"]
        else:
            continue
        n["routes"].append(i)
        r["node"] = n["id"]
        merge_tags(n, r)

    # 2. remote prefixes hang under the next hop, which is a neighbor of the interface
    for i, r in good:
        if r["kind"] not in ("remote", "default"):
            continue
        fam, iface, g = r["family"], r["iface"], r["gw"]
        if g["kind"] == "ip":
            gid = "nb:%d:%s:%s" % (fam, iface, g["ip"])
            if "self:%d:%s:%s" % (fam, iface, g["ip"]) in nodes:
                gid = "self:%d:%s:%s" % (fam, iface, g["ip"])  # next hop is this host itself
            gw = add(gid, kind="neighbor", label=g["ip"], family=fam,
                     addr=g["ip"], plen=FAMILY_MAX[fam],
                     bits=format(int(ipaddress.ip_address(g["ip"])), "0%db" % FAMILY_MAX[fam]))
            if "router" not in gw["tags"]:
                gw["tags"].append("router")
            if ipaddress.ip_address(g["ip"]).is_link_local and "linklocal" not in gw["tags"]:
                gw["tags"].append("linklocal")
            parent = gw["id"]
        else:
            parent = "if:" + iface
        n = add("rt:%d:%s:%s:%s" % (fam, iface, g["ip"] or g["raw"], r["cidr"]), kind=r["kind"], label=r["cidr"],
                family=fam, parent=parent, addr=str(r["net"].network_address), plen=r["plen"], bits=r["bits"])
        n["routes"].append(i)
        r["node"] = n["id"]
        merge_tags(n, r)

    # 3. neighbors and own addresses go under the most specific connected prefix on their interface
    nets = [n for n in nodes.values() if n["kind"] == "net"]
    for n in nodes.values():
        if n["kind"] not in ("neighbor", "self") or n["parent"]:
            continue
        iface = n["id"].split(":", 3)[2]
        ip = ipaddress.ip_address(n["addr"])
        best = None
        for m in nets:
            if m["family"] != n["family"] or m["parent"] != "if:" + iface or m["plen"] >= FAMILY_MAX[n["family"]]:
                continue
            if ip in ipaddress.ip_network("%s/%d" % (m["addr"], m["plen"])) and (best is None or m["plen"] > best["plen"]):
                best = m
        n["parent"] = best["id"] if best else "if:" + iface
        if best and n["family"] == 4 and ip == ipaddress.ip_network("%s/%d" % (best["addr"], best["plen"])).broadcast_address:
            for t in ("broadcast", "bookkeeping"):
                if t not in n["tags"]:
                    n["tags"].append(t)
        if n["kind"] == "self":
            # an own address delivered via lo0 usually belongs to another interface's prefix
            # (link-local ones say which interface with their %scope)
            for m in nets:
                owner = m["parent"][3:]
                if m["family"] != n["family"] or m["plen"] >= FAMILY_MAX[n["family"]] \
                        or is_loopback_iface(owner) or nodes[m["parent"]].get("info") \
                        or (n.get("scope") and n["scope"] != owner) \
                        or (ip.is_link_local and not n.get("scope")) \
                        or ip not in ipaddress.ip_network("%s/%d" % (m["addr"], m["plen"])):
                    continue
                ifn = nodes[m["parent"]]
                if not any(a.split("/")[0] == n["addr"] for a in ifn["addrs"]):
                    ifn["addrs"].append("%s/%d" % (n["addr"], m["plen"]))

    # 4. children lists, ordered the way a reader expects
    def child_key(c):
        k = c["kind"]
        ip = int(ipaddress.ip_address(c["addr"])) if c.get("addr") else 0
        if k == "iface":
            return (0, _iface_sort_key(c["label"]))
        if k == "net":
            return (1, c["family"], "bookkeeping" in c["tags"], "multicast" in c["tags"], c["plen"], ip)
        if k in ("neighbor", "self"):
            return (2, c["family"], k == "self", "router" not in c["tags"], "unresolved" in c["tags"], ip)
        return (3, c["family"], c["plen"], ip)

    for n in nodes.values():
        if n["parent"]:
            nodes[n["parent"]]["children"].append(n["id"])
    for n in nodes.values():
        n["children"].sort(key=lambda cid: child_key(nodes[cid]))

    # 5. labels
    for n in nodes.values():
        describe(n, nodes, routes)
    return nodes


def describe(n, nodes, routes):
    k, tags = n["kind"], n["tags"]
    rs = [routes[i] for i in n["routes"]]
    if k == "iface":
        bits = []
        if n.get("desc"):
            bits.append(n["desc"])
        info = n.get("info") or {}
        if info.get("status"):
            bits.append("status " + info["status"])
        if info.get("ether"):
            bits.append("MAC " + info["ether"])
        n["addrs"].sort(key=lambda a: (":" in a, a))
        n["sub"] = (n["addrs"][0] + (" +%d" % (len(n["addrs"]) - 1) if len(n["addrs"]) > 1 else "")) if n["addrs"] else ""
        n["note"] = "; ".join(bits)
    elif k == "net":
        what = "directly connected: hosts here are reached without a router"
        if "multicast" in tags:
            what = "multicast group range on this link"
        elif "linklocal" in tags:
            what = "link-local: valid only on this link, never routed"
        elif "loopback" in tags:
            what = "loopback network"
        elif "bookkeeping" in tags:
            what = "host-sized prefix the OS adds for its own bookkeeping"
        n["sub"] = "%d neighbor%s" % (len(n["children"]), "" if len(n["children"]) == 1 else "s") if n["children"] else ""
        n["note"] = what
    elif k == "neighbor":
        parts = []
        if "router" in tags:
            parts.append("router (next hop)")
        if n.get("mac"):
            parts.append(n["mac"])
        if "unresolved" in tags:
            parts.append("no MAC (ARP/NDP unresolved)")
        elif "reject" in tags:
            parts.append("unreachable")
        if "hostroute" in tags:
            parts.append("host route")
        n["sub"] = " · ".join(parts)
        n["note"] = ("next hop for %d route%s" % (len(n["children"]), "" if len(n["children"]) == 1 else "s")
                     if n["children"] else "a host on this link (ARP/NDP cache entry)")
        if n.get("expire"):
            n["note"] += "; cache entry expires in %ss" % n["expire"]
    elif k == "self":
        n["sub"] = "this host"
        n["note"] = "one of this host's own addresses; delivered locally via loopback"
        if n["children"]:
            n["sub"] += " · next hop for %d route%s" % (len(n["children"]), "" if len(n["children"]) == 1 else "s")
    if "broadcast" in tags and k in ("neighbor", "self"):
        n["sub"] = "broadcast address"
        n["note"] = "the all-hosts broadcast address of this prefix (or the link)"
    elif k in ("remote", "default"):
        if k == "default":
            n["label"] = "default"
            n["sub"] = "everything else (%s)" % n["id"].rsplit(":", 1)[1]
        else:
            n["sub"] = "via " + (rs[0]["gw"]["ip"] if rs and rs[0]["gw"]["ip"] else "the interface")
        n["note"] = "forwarded to the next hop; the router decides the rest"
        if "static" in tags:
            n["note"] += "; static (set by hand or DHCP)"
        if "scoped" in tags:
            n["sub"] += " · scoped to " + n["id"].split(":")[2]
            n["note"] = "interface-scoped duplicate of the default route: used only by sockets bound to this interface"
    if "reject" in tags and k != "neighbor":
        n["sub"] = (n["sub"] + " · " if n["sub"] else "") + "reject"


# --------------------------------------------------------------------------- longest-prefix match

def lookup(routes, text):
    """Which route does a packet to `text` take? Longest prefix wins."""
    ip = ipaddress.ip_address(text)
    cands = [r for r in routes if r.get("ok") and r["family"] == ip.version and ip in r["net"]]
    cands.sort(key=lambda r: -r["plen"])
    if not cands:
        return {"addr": str(ip), "winner": None, "candidates": []}
    winner = cands[0]
    network = next((r for r in cands if r["kind"] in ("connected", "remote", "default")), None)
    return {"addr": str(ip), "winner": winner, "network": network, "candidates": cands}


def explain_lookup(res, nodes):
    if not res["winner"]:
        return "no route to %s (the packet would be dropped: 'No route to host')" % res["addr"]
    w = res["winner"]
    out = ["packet to %s" % res["addr"]]
    out.append("  matches %d route%s; longest prefix wins:" % (len(res["candidates"]), "" if len(res["candidates"]) == 1 else "s"))
    for r in res["candidates"]:
        mark = "->" if r is w else "  "
        out.append("  %s %-28s %-22s %-10s %s" % (mark, r["cidr"], r["gateway"], r["flags"], r["iface"]))
    ties = [r for r in res["candidates"] if r["plen"] == w["plen"]]
    if len(ties) > 1:
        scoped = sum(1 for r in ties[1:] if "I" in r["flags"] and r["os"] == "bsd")
        out.append("  (%d routes tie on prefix length; the first in table order wins%s)" % (
            len(ties), "; the %d marked I are interface-scoped and only apply to sockets bound to that interface" % scoped
            if scoped else ""))
    k = w["kind"]
    if k in ("remote", "default"):
        out.append("  => send out %s to next hop %s (it forwards toward %s)" % (w["iface"], w["gw"]["ip"], w["cidr"]))
    elif k == "connected":
        out.append("  => %s is directly on %s: resolve its MAC with ARP/NDP and send to it" % (res["addr"], w["iface"]))
    elif k == "neighbor":
        mac = w["gw"]["mac"] or "(not resolved yet)"
        net = res.get("network")
        out.append("  => %s is a host on %s; MAC %s already cached%s" % (
            res["addr"], w["iface"], mac, (", cloned from %s" % net["cidr"]) if net else ""))
    elif k == "self":
        out.append("  => that is this host itself; delivered over %s" % w["iface"])
    return "\n".join(out)


def path_to_root(nodes, nid):
    path = []
    while nid:
        path.append(nid)
        nid = nodes[nid]["parent"]
    return list(reversed(path))


# --------------------------------------------------------------------------- filtering

HIDE_DEFAULT = ("multicast", "bookkeeping", "linklocal")


def visible_set(nodes, hide=HIDE_DEFAULT, families=(4, 6)):
    """Nodes to draw: those passing the filters plus every ancestor of one that does."""
    hide = set(hide)
    vis = set()

    def passes(n):
        if n["family"] and n["family"] not in families:
            return False
        if n["kind"] in ("neighbor", "self") and "neighbors" in hide and "router" not in n["tags"]:
            return False
        if "loopback" in hide and (n["kind"] == "self" or "loopback" in n["tags"]
                                   or (n["kind"] == "iface" and is_loopback_iface(n["label"]))):
            return False
        return not any(t in hide for t in n["tags"] if t != "loopback")

    def walk(nid):
        n = nodes[nid]
        # an interface, or a next hop that has no entry of its own, shows only if something under it does
        keep = passes(n) and n["kind"] != "iface" and not (n["kind"] == "neighbor" and not n["routes"])
        for c in n["children"]:
            keep = walk(c) or keep
        if keep or nid == "host":
            vis.add(nid)
        return keep

    walk("host")
    return vis


# --------------------------------------------------------------------------- text / dot

def render_text(nodes, routes, vis, highlight=()):
    hl = set(highlight)
    out = []

    def line(n, prefix, branch, last):
        mark = "*" if n["id"] in hl else " "
        bits = [n["label"]]
        if n["sub"]:
            bits.append(n["sub"])
        rs = [routes[i] for i in n["routes"]]
        if rs:
            bits.append("(%s)" % ", ".join(sorted({r["flags"] for r in rs if r["flags"]})) if any(r["flags"] for r in rs) else "")
        if n["kind"] == "iface" and n.get("desc"):
            bits.append("- " + n["desc"])
        elif n["kind"] == "net" and n["note"]:
            bits.append("- " + n["note"].split(":")[0])
        out.append("%s%s%s %s" % (mark, prefix, branch, "  ".join(b for b in bits if b)))
        kids = [nodes[c] for c in n["children"] if c in vis]
        ext = prefix + ("   " if last else "│  ") if branch else prefix
        for i, k in enumerate(kids):
            line(k, ext, "└─ " if i == len(kids) - 1 else "├─ ", i == len(kids) - 1)

    line(nodes["host"], "", "", True)
    return "\n".join(out)


DOT_COLORS = {"host": "#f0e442", "iface": "#56b4e9", "net": "#cfe9d9", "neighbor": "#f4cfa8",
              "self": "#e8e8e8", "remote": "#ddd3f2", "default": "#e69f00"}


def render_dot(nodes, routes, vis):
    out = ["digraph routes {", "  rankdir=LR; splines=true; nodesep=0.15; ranksep=0.7;",
           '  node [shape=box, style="rounded,filled", fontname="Helvetica", fontsize=10];',
           '  edge [color="#888888", arrowsize=0.6];']
    for nid in vis:
        n = nodes[nid]
        label = n["label"] + ("\\n" + n["sub"] if n["sub"] else "")
        style = "rounded,filled" + (",dashed" if "reject" in n["tags"] or "unresolved" in n["tags"] else "")
        out.append('  "%s" [label="%s", fillcolor="%s", style="%s"];' % (
            nid, label.replace('"', '\\"'), DOT_COLORS.get(n["kind"], "#ffffff"), style))
    for nid in vis:
        n = nodes[nid]
        for c in n["children"]:
            if c in vis:
                w = ' [penwidth=2, color="#d55e00"]' if nodes[c]["kind"] == "default" else ""
                out.append('  "%s" -> "%s"%s;' % (nid, c, w))
    out.append("}")
    return "\n".join(out)


# --------------------------------------------------------------------------- static svg

COLUMNS = [("host", "this host"), ("iface", "interfaces"), ("net", "connected prefixes"),
           ("neighbor", "next hops & neighbors"), ("remote", "remote prefixes")]
COL_OF = {"host": 0, "iface": 1, "net": 2, "neighbor": 3, "self": 3, "remote": 4, "default": 4}


def layout(nodes, vis, pitch=46, gap=64, char_w=7.0):
    """Tidy tree: leaves get successive rows, parents sit at the middle of their children.
    Returns (positions {id: [x, y, w, h]}, width, height, column x/width list)."""
    widths = [90] * len(COLUMNS)
    for nid in vis:
        n = nodes[nid]
        c = COL_OF[n["kind"]]
        widths[c] = max(widths[c], min(340, int(max(len(n["label"]), len(n["sub"]) * 0.85) * char_w) + 22))
    xs, x = [], 16
    for w in widths:
        xs.append(x)
        x += w + gap
    pos, slot = {}, [0]

    def place(nid):
        n = nodes[nid]
        kids = [c for c in n["children"] if c in vis]
        if kids:
            ys = [place(c) for c in kids]
            y = (ys[0] + ys[-1]) / 2.0
        else:
            y = 40 + slot[0] * pitch
            slot[0] += 1
        c = COL_OF[n["kind"]]
        h = 38 if n["sub"] else 26
        pos[nid] = [xs[c], y - h / 2.0, widths[c], h]
        return y

    place("host")
    height = 40 + max(slot[0], 1) * pitch
    return pos, x - gap + 16, height, list(zip(xs, widths))


SVG_CSS = """
  text { font: 12px ui-monospace, Menlo, Consolas, monospace; fill: #1a1a19; }
  .sub { font-size: 10px; fill: #52514e; }
  .col { font: 600 11px -apple-system, Helvetica, Arial, sans-serif; fill: #52514e; letter-spacing: .04em; }
  .edge { fill: none; stroke: #b3b1a8; stroke-width: 1.4; }
  .edge.default { stroke: #eb6834; stroke-width: 2.4; }
  .edge.dashed { stroke-dasharray: 4 3; }
  .edge.hl { stroke: #2a78d6; stroke-width: 3; }
  rect { rx: 6; stroke-width: 1.2; }
  .host rect { fill: #fff3c4; stroke: #eda100; }
  .iface rect { fill: #dcebfb; stroke: #2a78d6; }
  .net rect { fill: #d9f3e7; stroke: #1baf7a; }
  .neighbor rect { fill: #fbe3d6; stroke: #eb6834; }
  .self rect { fill: #ededea; stroke: #8b8a83; }
  .remote rect, .default rect { fill: #e5e1f7; stroke: #4a3aa7; }
  .default rect { stroke-width: 2.2; }
  .dim rect { stroke-dasharray: 4 3; opacity: .75; }
  .hl rect { stroke: #2a78d6; stroke-width: 3; }
"""


def render_svg(nodes, routes, vis, highlight=()):
    hl = set(highlight)
    pos, W, H, cols = layout(nodes, vis)
    out = ['<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">' % (W, H, W, H),
           "<style>%s</style>" % SVG_CSS, '<rect width="100%" height="100%" fill="#fcfcfb"/>']
    for (x, w), (_, title) in zip(cols, COLUMNS):
        out.append('<text class="col" x="%d" y="18">%s</text>' % (x, html.escape(title.upper())))
    for nid in vis:
        n = nodes[nid]
        for c in n["children"]:
            if c not in vis:
                continue
            x1, y1, w1, h1 = pos[nid]
            x2, y2, w2, h2 = pos[c]
            ax, ay, bx, by = x1 + w1, y1 + h1 / 2, x2, y2 + h2 / 2
            mx = (ax + bx) / 2
            k = nodes[c]
            cls = "edge" + (" default" if k["kind"] == "default" else "") \
                + (" dashed" if "reject" in k["tags"] or "unresolved" in k["tags"] else "") \
                + (" hl" if nid in hl and c in hl else "")
            out.append('<path class="%s" d="M%.1f %.1f C%.1f %.1f %.1f %.1f %.1f %.1f"/>' % (cls, ax, ay, mx, ay, mx, by, bx, by))
    for nid in vis:
        n = nodes[nid]
        x, y, w, h = pos[nid]
        cls = n["kind"] + (" dim" if "reject" in n["tags"] or "unresolved" in n["tags"] else "") + (" hl" if nid in hl else "")
        out.append('<g class="%s"><title>%s</title><rect x="%.1f" y="%.1f" width="%d" height="%d"/>' % (
            cls, html.escape(node_tooltip(n, routes)), x, y, w, h))
        if n["sub"]:
            out.append('<text x="%.1f" y="%.1f">%s</text><text class="sub" x="%.1f" y="%.1f">%s</text>' % (
                x + 9, y + 15, html.escape(n["label"]), x + 9, y + 30, html.escape(n["sub"][:48])))
        else:
            out.append('<text x="%.1f" y="%.1f">%s</text>' % (x + 9, y + 17, html.escape(n["label"])))
        out.append("</g>")
    out.append("</svg>")
    return "\n".join(out)


def node_tooltip(n, routes):
    lines = [n["label"] + (" - " + n["sub"] if n["sub"] else "")]
    if n["note"]:
        lines.append(n["note"])
    for i in n["routes"]:
        r = routes[i]
        lines.append(r["raw"].strip())
        lines.extend("  " + f for f in explain_flags(r))
    return "\n".join(lines)


# --------------------------------------------------------------------------- html / json

def route_json(r):
    keep = ("family", "dest", "gateway", "flags", "iface", "expire", "raw", "extra", "os", "ok",
            "cidr", "plen", "scope", "bits", "gw", "kind", "tags", "node")
    d = {k: r.get(k) for k in keep if k in r}
    if r.get("ok"):
        d["flags_explained"] = explain_flags(r)
    return d


def payload(nodes, routes, meta, hostname, source, lookups=()):
    return {
        "hostname": hostname, "source": source, "generated": dt.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "os": meta.get("os"), "hide_default": list(HIDE_DEFAULT),
        "columns": COLUMNS, "routes": [route_json(r) for r in routes], "nodes": nodes,
        "glossary": flag_glossary(routes), "lookups": list(lookups),
    }


def render_html(data):
    tpl = TEMPLATE.read_text(encoding="utf-8")
    js = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    return tpl.replace("__DATA__", js).replace("__TITLE__", html.escape("routes: " + data["hostname"]))


# --------------------------------------------------------------------------- cli

def run(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError) as e:
        sys.exit("could not run %s: %s" % (" ".join(cmd), e))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter,
                                 epilog=__doc__.split("\n", 2)[2])
    ap.add_argument("input", nargs="?", help="file with `netstat -rn` output ('-' = stdin; default: stdin if piped, else --live)")
    ap.add_argument("-f", "--format", choices=("html", "svg", "text", "dot", "json"), default="html")
    ap.add_argument("-o", "--output", help="output file (html defaults to routes.html; other formats to stdout)")
    ap.add_argument("--live", action="store_true", help="run `netstat -rn` (and ifconfig) on this machine")
    ap.add_argument("--ifconfig", metavar="FILE", help="ifconfig -a / ip addr output to label interfaces with")
    ap.add_argument("--hostname", help="name for the host node")
    ap.add_argument("--to", action="append", default=[], metavar="ADDR",
                    help="explain the longest-prefix match for ADDR and highlight it (repeatable)")
    ap.add_argument("--all", action="store_true", help="text/svg/dot: include multicast and bookkeeping routes")
    ap.add_argument("--hide", default=",".join(HIDE_DEFAULT),
                    help="text/svg/dot: comma list of multicast,bookkeeping,linklocal,loopback,neighbors,reject")
    ap.add_argument("--open", action="store_true", help="open the html output in the browser")
    a = ap.parse_args(argv)

    ifcfg_text, source = "", ""
    if a.input and a.input != "-":
        text = pathlib.Path(a.input).read_text(encoding="utf-8", errors="replace")
        source = "from %s" % a.input
    elif a.input == "-" or (not a.live and not sys.stdin.isatty()):
        text = sys.stdin.read()
        source = "from stdin"
    else:
        a.live = True
        text = run(["netstat", "-rn"])
        source = "netstat -rn on %s" % socket.gethostname()
        if sys.platform == "darwin":
            ifcfg_text = run(["ifconfig", "-a"])
        elif sys.platform.startswith("linux"):
            try:
                ifcfg_text = subprocess.run(["ip", "addr"], capture_output=True, text=True, check=True).stdout
            except (OSError, subprocess.CalledProcessError):
                ifcfg_text = ""
    if a.ifconfig:
        ifcfg_text = pathlib.Path(a.ifconfig).read_text(encoding="utf-8", errors="replace")
    hostname = a.hostname or (socket.gethostname() if a.live else "this host")

    try:
        routes, meta = parse_netstat(text)
    except ParseError as e:
        sys.exit("routeviz: %s" % e)
    classify(routes)
    ifcfg = parse_ifconfig(ifcfg_text) if ifcfg_text else {}
    nodes = build_graph(routes, ifcfg, hostname, source)

    lookups, highlight = [], []
    for addr in a.to:
        try:
            res = lookup(routes, addr)
        except ValueError:
            sys.exit("routeviz: not an IP address: %s" % addr)
        lookups.append({"addr": res["addr"], "node": res["winner"]["node"] if res["winner"] else None,
                        "text": explain_lookup(res, nodes)})
        if res["winner"]:
            highlight.extend(path_to_root(nodes, res["winner"]["node"]))
        if a.format != "json":
            print(explain_lookup(res, nodes), file=sys.stderr if a.format != "text" else sys.stdout)
            if a.format == "text":
                print()

    hide = () if a.all else tuple(h for h in a.hide.split(",") if h)
    vis = visible_set(nodes, hide)
    if a.format == "html":
        out = render_html(payload(nodes, routes, meta, hostname, source, lookups))
    elif a.format == "svg":
        out = render_svg(nodes, routes, vis, highlight)
    elif a.format == "text":
        out = render_text(nodes, routes, vis, highlight)
    elif a.format == "dot":
        out = render_dot(nodes, routes, vis)
    else:
        out = json.dumps(payload(nodes, routes, meta, hostname, source, lookups), indent=1, ensure_ascii=False)

    if a.format == "html" and a.output != "-":
        path = pathlib.Path(a.output or "routes.html")
        path.write_text(out, encoding="utf-8")
        n4 = sum(1 for r in routes if r.get("ok") and r["family"] == 4)
        n6 = sum(1 for r in routes if r.get("ok") and r["family"] == 6)
        print("wrote %s (%d IPv4 + %d IPv6 routes, %d nodes)" % (path, n4, n6, len(nodes)), file=sys.stderr)
        if a.open:
            opener = {"darwin": "open", "win32": "start"}.get(sys.platform, "xdg-open")
            subprocess.call([opener, str(path)])
    elif a.output and a.output != "-":
        pathlib.Path(a.output).write_text(out + "\n", encoding="utf-8")
    else:
        sys.stdout.write(out + "\n")


if __name__ == "__main__":
    main()
