// ===================================================================== model: netstat -rn -> tree
const FAMILY_MAX = { 4: 32, 6: 128 };
const BSD_FLAGS = {
  U: ['RTF_UP', 'route is usable'], G: ['RTF_GATEWAY', 'destination needs forwarding by an intermediary (a next hop)'],
  H: ['RTF_HOST', 'host entry (a single address, not a network)'], S: ['RTF_STATIC', 'added manually or by DHCP, not learned from the link'],
  C: ['RTF_CLONING', 'generates new host routes on use (per-neighbor ARP/NDP entries)'], c: ['RTF_PRCLONING', 'protocol-specified cloning'],
  W: ['RTF_WASCLONED', 'was generated by a cloning route (an ARP/NDP cache entry)'], L: ['RTF_LLINFO', 'holds a link-layer (MAC) address for the destination'],
  D: ['RTF_DYNAMIC', 'created dynamically by an ICMP redirect'], M: ['RTF_MODIFIED', 'modified dynamically by an ICMP redirect'],
  R: ['RTF_REJECT', 'host or net unreachable (packets are rejected)'], B: ['RTF_BLACKHOLE', 'packets are silently discarded'],
  b: ['RTF_BROADCAST', 'destination is a broadcast address'], m: ['RTF_MULTICAST', 'destination is a multicast address'],
  I: ['RTF_IFSCOPE', 'route is scoped to one interface'], i: ['RTF_IFREF', 'route holds a reference to its interface'],
  r: ['RTF_ROUTER', 'this host is a default router (advertised itself)'], g: ['RTF_GLOBAL', 'policy hint: destination is on the global Internet'],
  X: ['RTF_XRESOLVE', 'an external daemon resolves the link address'], Y: ['RTF_PROXY', 'proxying; cloned routes are not scoped'],
  1: ['RTF_PROTO1', 'protocol-specific flag 1'], 2: ['RTF_PROTO2', 'protocol-specific flag 2'], 3: ['RTF_PROTO3', 'protocol-specific flag 3'],
};
const LINUX_FLAGS = {
  U: ['up', 'route is usable'], G: ['gateway', 'destination needs forwarding by an intermediary (a next hop)'],
  H: ['host', 'host entry (a single address, not a network)'], R: ['reinstate', 'reinstate route for dynamic routing'],
  D: ['dynamic', 'installed by a routing daemon or an ICMP redirect'], M: ['modified', 'modified by a routing daemon or an ICMP redirect'],
  A: ['addrconf', 'installed by IPv6 address autoconfiguration'], C: ['cache', 'cache entry (a resolved neighbor)'],
  e: ['expires', 'the entry expires'], n: ['nonexthop', 'no next hop (delivered on the link)'], '!': ['reject', 'reject route (packets are dropped)'],
};
const IFACE_KINDS = [
  [/^lo\d*$/, 'loopback (packets to this host itself)'], [/^en\d+$/, 'Ethernet / Wi-Fi (en0 is usually Wi-Fi on a MacBook)'],
  [/^(eth|eno|ens|enp|em)\d/, 'Ethernet'], [/^(wlan|wlp|wlo|wl)\w*/, 'Wi-Fi'],
  [/^utun\d+$/, 'userspace tunnel (VPN, iCloud Private Relay, Tailscale, ...)'], [/^(tun|tap)\d+$/, 'tunnel (VPN)'],
  [/^wg\d+$/, 'WireGuard tunnel'], [/^ppp\d+$/, 'point-to-point link'], [/^awdl\d+$/, 'Apple Wireless Direct Link (AirDrop, Sidecar)'],
  [/^llw\d+$/, 'low-latency WLAN (companion to awdl)'], [/^ap\d+$/, 'Wi-Fi access point (hotspot / Internet Sharing)'],
  [/^bridge\d+$/, 'software bridge (Internet Sharing, VMs)'], [/^(docker\d+|br-[0-9a-f]+)$/, 'Docker bridge'],
  [/^veth/, 'virtual Ethernet pair (container)'], [/^(vmnet|vboxnet|virbr)\d+$/, 'VM host-only / NAT network'],
  [/^gif\d+$/, 'generic IP-in-IP tunnel'], [/^stf\d+$/, '6to4 tunnel'], [/^anpi\d+$/, 'Apple debug/USB interface'], [/^ipsec\d+$/, 'IPsec tunnel'],
];
const isLo = (n) => /^lo\d*$/.test(n) || n === '127.0.0.1';
const ifaceKind = (n) => { for (const [re, d] of IFACE_KINDS) if (re.test(n)) return d; return ''; };

// ---- addresses as bit strings (so prefix match is startsWith)
function v4bits(s) {
  const m = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(s); if (!m) return null;
  const o = m.slice(1).map(Number); if (o.some((x) => x > 255)) return null;
  return o.map((x) => x.toString(2).padStart(8, '0')).join('');
}
function v6bits(s) {
  if (s.includes('.')) { const i = s.lastIndexOf(':'), v4 = v4bits(s.slice(i + 1)); if (!v4) return null;
    s = s.slice(0, i + 1) + parseInt(v4.slice(0, 16), 2).toString(16) + ':' + parseInt(v4.slice(16), 2).toString(16); }
  const parts = s.split('::'); if (parts.length > 2) return null;
  const head = parts[0] ? parts[0].split(':') : [], tail = parts[1] ? parts[1].split(':') : [];
  if (parts.length === 1 && head.length !== 8) return null;
  if (head.length + tail.length > 8) return null;
  const groups = head.concat(Array(8 - head.length - tail.length).fill('0'), tail);
  let bits = '';
  for (const g of groups) { if (!/^[0-9a-f]{1,4}$/i.test(g)) return null; bits += parseInt(g, 16).toString(2).padStart(16, '0'); }
  return bits;
}
function addrBits(s) { s = s.split('%')[0]; return s.includes(':') ? { fam: 6, bits: v6bits(s) } : { fam: 4, bits: v4bits(s) }; }
function fmt4(b) { return [0, 8, 16, 24].map((i) => parseInt(b.slice(i, i + 8), 2)).join('.'); }
function fmt6(b) {
  const g = []; for (let i = 0; i < 128; i += 16) g.push(parseInt(b.slice(i, i + 16), 2));
  let best = -1, bestLen = 0, cur = -1, curLen = 0;
  for (let i = 0; i < 8; i++) { if (g[i] === 0) { if (cur < 0) { cur = i; curLen = 1; } else curLen++; if (curLen > bestLen) { best = cur; bestLen = curLen; } } else { cur = -1; curLen = 0; } }
  const hex = g.map((x) => x.toString(16));
  return bestLen >= 2 ? hex.slice(0, best).join(':') + '::' + hex.slice(best + bestLen).join(':') : hex.join(':');
}
const fmt = (b, fam) => (fam === 4 ? fmt4(b) : fmt6(b));
const netBits = (b, plen) => b.slice(0, plen) + '0'.repeat(b.length - plen);
const popcount = (b) => (b.match(/1/g) || []).length;
const LL4 = v4bits('169.254.0.0').slice(0, 16), LL6 = '1111111010', LOOP6 = '0'.repeat(127) + '1';
const isLinkLocalBits = (b, fam) => (fam === 4 ? b.startsWith(LL4) : b.startsWith(LL6));


// ---- what kind of address is this? (longest matching class wins)
const PRIV = 'RFC 1918 private range: never routed on the Internet; the home router rewrites it to the public address (NAT)';
const ADDR_CLASSES = {
  4: [
    ['0.0.0.0/8', 'unspecified', '"this network"; 0.0.0.0 in a table means "any address"'],
    ['10.0.0.0/8', 'private', PRIV], ['172.16.0.0/12', 'private', PRIV], ['192.168.0.0/16', 'private', PRIV],
    ['100.64.0.0/10', 'carrier-grade NAT', 'RFC 6598 shared space: ISPs NAT it a second time; Tailscale hands these out too'],
    ['127.0.0.0/8', 'loopback', 'this host itself; never leaves the machine'],
    ['169.254.0.0/16', 'link-local', 'self-assigned when DHCP fails; valid on one link only, never routed'],
    ['192.0.2.0/24', 'documentation', 'reserved for examples'], ['198.51.100.0/24', 'documentation', 'reserved for examples'], ['203.0.113.0/24', 'documentation', 'reserved for examples'],
    ['198.18.0.0/15', 'benchmarking', 'reserved for network testing'],
    ['224.0.0.0/4', 'multicast', 'one-to-many group address; its MAC is computed from the IP (01:00:5e + low 23 bits), not learned by ARP'],
    ['255.255.255.255/32', 'broadcast', 'limited broadcast: every host on the link'],
    ['240.0.0.0/4', 'reserved', 'reserved by IANA'],
  ],
  6: [
    ['::/128', 'unspecified', 'no address yet'], ['::1/128', 'loopback', 'this host itself'],
    ['::ffff:0:0/96', 'IPv4-mapped', 'an IPv4 address carried inside an IPv6 socket'],
    ['64:ff9b::/96', 'NAT64', 'how IPv6-only networks reach IPv4 through a translator'],
    ['fe80::/10', 'link-local', 'every interface has one (from the MAC or random); NDP and router advertisements live here; needs a %zone because every link has the same prefix'],
    ['fc00::/7', 'unique local', 'the IPv6 cousin of private addresses: routed inside a site, never on the Internet'],
    ['ff00::/8', 'multicast', 'group address; ff02:: is link scope (ff02::1 all nodes, ff02::2 all routers), ff01:: interface scope'],
    ['2001:db8::/32', 'documentation', 'reserved for examples'], ['2002::/16', '6to4', 'IPv6 tunneled over IPv4'], ['2001::/32', 'Teredo', 'IPv6 tunneled over UDP/IPv4'],
    ['2000::/3', 'global unicast', 'a real Internet address: no NAT, this is what the world sees'],
  ],
};
const CLASS_BITS = {};
for (const fam of [4, 6]) CLASS_BITS[fam] = ADDR_CLASSES[fam].map(([c, label, note]) => { const [a, p] = c.split('/'); const b = fam === 4 ? v4bits(a) : v6bits(a); return { bits: b.slice(0, Number(p)), plen: Number(p), label, note }; });
function addrClass(bits, fam, plen) {
  if (plen === 0) return { label: 'everything', note: 'the default route covers the whole address space' };
  let best = null;
  for (const c of CLASS_BITS[fam]) if (bits.startsWith(c.bits) && (!best || c.plen > best.plen)) best = c;
  return best || (fam === 4 ? { label: 'public', note: 'globally routable: an Internet address' } : { label: 'reserved', note: 'not currently allocated' });
}
// ---- the two flag bits in the first byte of a MAC
function macInfo(mac) {
  const b = parseInt(mac.slice(0, 2), 16);
  return { multicast: !!(b & 1), random: !!(b & 2) && !(b & 1) };
}
// ---- address anatomy for a prefix
function anatomy(netbits, plen, fam) {
  const max = FAMILY_MAX[fam], hostBits = max - plen;
  const first = netbits, last = netbits.slice(0, plen) + '1'.repeat(hostBits);
  let count;
  if (fam === 4) count = plen >= 31 ? (plen === 32 ? '1 address' : '2 addresses') : `${(2 ** hostBits - 2).toLocaleString()} usable hosts`;
  else count = hostBits === 0 ? '1 address' : `2^${hostBits} addresses`;
  return { mask: fam === 4 ? fmt4('1'.repeat(plen) + '0'.repeat(hostBits)) : `/${plen}`, first: fmt(first, fam), last: fmt(last, fam), count, groups: fam === 4 ? 8 : 16 };
}

function parseDest4(text) {
  if (text === 'default') return { bits: '0'.repeat(32), plen: 0 };
  let plen = null; if (text.includes('/')) { const [a, p] = text.split('/'); text = a; plen = Number(p); }
  const oct = text.split('.'); if (oct.length > 4 || oct.some((o) => !/^\d+$/.test(o) || Number(o) > 255)) return null;
  if (plen === null) plen = oct.length === 4 ? 32 : 8 * oct.length;
  while (oct.length < 4) oct.push('0');
  const bits = v4bits(oct.join('.')); if (!bits || !(plen >= 0 && plen <= 32)) return null;
  return { bits: netBits(bits, plen), plen };
}
function parseDest6(text) {
  if (text === 'default') return { bits: '0'.repeat(128), plen: 0, scope: '' };
  let plen = null; if (text.includes('/')) { const [a, p] = text.split('/'); text = a; plen = Number(p); }
  const [addr, scope = ''] = text.split('%'); const bits = v6bits(addr); if (!bits) return null;
  if (plen === null) plen = 128; if (!(plen >= 0 && plen <= 128)) return null;
  return { bits: netBits(bits, plen), plen, scope };
}
const MAC_RE = /^(?:[0-9a-f]{1,2}:){5}[0-9a-f]{1,2}$/i, LINK_RE = /^link#(\d+)$/;
function parseGateway(text) {
  const g = { kind: 'none', ip: '', scope: '', link: '', mac: '', raw: text, bits: '', fam: 0 };
  if (!text || ['0.0.0.0', '::', '*', 'On-link', '-'].includes(text)) return g;
  const m = LINK_RE.exec(text); if (m) { g.kind = 'link'; g.link = m[1]; return g; }
  if (MAC_RE.test(text)) { g.kind = 'mac'; g.mac = text.split(':').map((x) => parseInt(x, 16).toString(16).padStart(2, '0')).join(':'); return g; }
  const [addr, scope = ''] = text.split('%'); const a = addrBits(addr); if (!a.bits) return g;
  Object.assign(g, { kind: 'ip', ip: fmt(a.bits, a.fam), scope, bits: a.bits, fam: a.fam }); return g;
}
const mkRoute = (family, dest, gateway, flags, iface, raw, os) => ({ family, dest, gateway, flags: flags || '', iface, expire: '', raw: raw.replace(/\s+$/, ''), extra: {}, os });

function parseNetstat(text) {
  const routes = [], meta = { os: null };
  let family = null, columns = null, layout = null, pending = null;
  for (const line of text.split(/\r?\n/)) {
    const s = line.trim(); if (!s) continue; const low = s.toLowerCase();
    if (low === 'internet:' || low === 'internet6:') { family = low.includes('6') ? 6 : 4; columns = null; continue; }
    if (low.startsWith('kernel ip routing table')) { family = 4; layout = 'linux4'; meta.os = meta.os || 'linux'; continue; }
    if (low.startsWith('kernel ipv6 routing table')) { family = 6; layout = 'linux6'; meta.os = meta.os || 'linux'; continue; }
    if (low.startsWith('ipv4 route table')) { family = 4; layout = 'win4'; meta.os = 'windows'; continue; }
    if (low.startsWith('ipv6 route table')) { family = 6; layout = 'win6'; meta.os = 'windows'; continue; }
    if (/^(routing tables|active routes|persistent routes|interface list|default gateway)/.test(low) || /^[=-]+$/.test(s)) continue;
    if (/^(network\s+destination|destination)\b/.test(low) || /^if\s+metric/.test(low)) {
      if (/^if\s+metric/.test(low)) { columns = ['If', 'Metric', 'Network Destination', 'Gateway']; layout = 'win6'; family = 6; }
      else if (low.startsWith('network destination')) { columns = ['Network Destination', 'Netmask', 'Gateway', 'Interface', 'Metric']; layout = 'win4'; family = 4; }
      else if (layout !== 'linux4' && layout !== 'linux6') { columns = s.split(/\s+/); layout = 'bsd'; meta.os = meta.os || 'bsd'; if (family === null) family = 4; }
      else columns = s.split(/\s+/);
      continue;
    }
    if (!columns) continue;
    const toks = s.split(/\s+/);
    if (layout === 'bsd') {
      const idx = {}; columns.forEach((c, i) => { idx[c.toLowerCase()] = i; });
      if (['destination', 'gateway', 'flags', 'netif'].some((k) => !(k in idx)) || toks.length <= idx.netif) continue;
      const r = mkRoute(family, toks[idx.destination], toks[idx.gateway], toks[idx.flags], toks[idx.netif], line, 'bsd');
      r.expire = 'expire' in idx && toks.length > idx.expire ? toks[idx.expire] : '';
      columns.forEach((c, i) => { const k = c.toLowerCase(); if (!['destination', 'gateway', 'flags', 'netif', 'expire'].includes(k) && i < toks.length) r.extra[c] = toks[i]; });
      if (family === 4 && r.dest.includes(':')) r.family = 6;
      routes.push(r);
    } else if (layout === 'linux4') {
      if (toks.length < 8) continue;
      const r = mkRoute(4, toks[0], toks[1], toks[3], toks[toks.length - 1], line, 'linux'); r.genmask = toks[2];
      r.extra = { Genmask: toks[2], Metric: toks[4], Ref: toks[5], Use: toks[6] }; routes.push(r);
    } else if (layout === 'linux6') {
      if (toks.length < 7) continue;
      const r = mkRoute(6, toks[0], toks[1], toks[2], toks[toks.length - 1], line, 'linux'); r.extra = { Metric: toks[3], Ref: toks[4], Use: toks[5] }; routes.push(r);
    } else if (layout === 'win4') {
      if (toks.length < 5) continue;
      const r = mkRoute(4, toks[0], toks[2], '', toks[3], line, 'windows'); r.genmask = toks[1]; r.extra = { Metric: toks[4] }; routes.push(r);
    } else if (layout === 'win6') {
      if (pending && toks.length === 1) { pending.gateway = toks[0]; pending.raw += ' ' + toks[0]; routes.push(pending); pending = null; continue; }
      pending = null;
      if (toks.length === 3) { pending = mkRoute(6, toks[2], '', '', 'if' + toks[0], line, 'windows'); pending.extra = { Metric: toks[1] }; continue; }
      if (toks.length < 4) continue;
      const r = mkRoute(6, toks[2], toks.slice(3).join(' '), '', 'if' + toks[0], line, 'windows'); r.extra = { Metric: toks[1] }; routes.push(r);
    }
  }
  if (!routes.length) throw new Error('No routes found. Paste the whole output of `netstat -rn` (macOS, Linux or Windows), headers included.');
  meta.os = meta.os || 'bsd';
  return { routes, meta };
}

function parseIfconfig(text) {
  const ifaces = {}; let cur = null;
  for (const line of text.split(/\r?\n/)) {
    const m = /^(?:\d+:\s+)?([A-Za-z][\w.\-]*?)(?:@\w+)?:\s/.exec(line);
    if (m && !/^[ \t]/.test(line)) { cur = ifaces[m[1]] = ifaces[m[1]] || { ether: '', inet: [], inet6: [], status: '', mtu: '' }; const mm = /mtu\s+(\d+)/.exec(line); if (mm) cur.mtu = mm[1]; continue; }
    if (!cur) continue; const s = line.trim(); let x;
    if ((x = /^(?:ether|link\/ether)\s+([0-9a-f:]{11,17})/i.exec(s))) { cur.ether = x[1].toLowerCase(); continue; }
    if ((x = /^inet\s+(\d+\.\d+\.\d+\.\d+)(?:\/(\d+))?(?:\s+netmask\s+(0x[0-9a-f]+|\d+\.\d+\.\d+\.\d+))?/i.exec(s))) {
      let plen = x[2]; if (!plen && x[3]) { const mask = x[3]; plen = mask.startsWith('0x') ? popcount(parseInt(mask, 16).toString(2)) : popcount(v4bits(mask) || ''); }
      cur.inet.push(x[1] + '/' + (plen || 32)); continue;
    }
    if ((x = /^inet6\s+([0-9a-f:]+)(?:%\w+)?(?:\/(\d+))?(?:\s+prefixlen\s+(\d+))?/i.exec(s))) { cur.inet6.push(x[1] + '/' + (x[2] || x[3] || 128)); continue; }
    if ((x = /^status:\s*(\w+)/.exec(s))) cur.status = x[1];
  }
  return ifaces;
}

function explainFlags(r) { const t = r.os === 'linux' ? LINUX_FLAGS : BSD_FLAGS; return [...r.flags].map((ch) => (ch in t ? `${ch} = ${t[ch][1]}` : `${ch} = ?`)); }
function flagGlossary(routes) {
  const out = {};
  for (const r of routes) { const t = r.os === 'linux' ? LINUX_FLAGS : BSD_FLAGS; for (const ch of r.flags) if (ch in t && !(ch in out)) out[ch] = { name: t[ch][0], meaning: t[ch][1] }; }
  return out;
}

function classify(routes) {
  for (const r of routes) {
    r.ok = false; let d = null;
    if (r.family === 4) {
      if (r.genmask) { const mb = v4bits(r.genmask), ab = v4bits(r.dest); if (mb && ab) { const plen = popcount(mb); d = { bits: netBits(ab, plen), plen }; } }
      else d = parseDest4(r.dest);
      if (d) d.scope = '';
    } else d = parseDest6(r.dest);
    if (!d) continue;
    r.ok = true; r.plen = d.plen; r.scope = d.scope || ''; r.netbits = d.bits; r.bits = d.bits.slice(0, d.plen);
    r.addr = fmt(d.bits, r.family); r.cidr = r.addr + '/' + d.plen;
    const g = parseGateway(r.gateway); r.gw = g;
    const flags = new Set(r.flags), win = r.os === 'windows', maxlen = FAMILY_MAX[r.family];
    const loopNet = r.family === 4 ? r.plen >= 8 && r.netbits.startsWith('01111111') : r.plen === 128 && r.netbits === LOOP6;
    const lo = isLo(r.iface) || (win && loopNet), hostSized = r.plen === maxlen;
    const isHost = flags.has('H') || (win && hostSized), hasGw = flags.has('G') || (win && g.kind === 'ip');
    const tags = new Set(); let kind;
    if (r.plen === 0) kind = 'default';
    else if (hasGw && g.kind === 'ip') kind = 'remote';
    else if (isHost) kind = lo || (win && r.addr === r.iface) ? 'self' : 'neighbor';
    else kind = 'connected';
    const multi = r.family === 4 ? r.plen >= 4 && r.netbits.startsWith('1110') : r.plen >= 8 && r.netbits.startsWith('11111111');
    const ll = r.family === 4 ? r.plen >= 16 && r.netbits.startsWith(LL4) : r.plen >= 10 && r.netbits.startsWith(LL6);
    if (multi || flags.has('m')) tags.add('multicast');
    if (ll) tags.add('linklocal');
    if (lo || loopNet) tags.add('loopback');
    if ((flags.has('R') && r.os === 'bsd') || flags.has('!')) tags.add('reject');
    if (flags.has('B') && r.os === 'bsd') tags.add('blackhole');
    if (flags.has('S') && r.os === 'bsd') tags.add('static');
    if ((flags.has('W') && r.os === 'bsd') || (flags.has('C') && r.os === 'linux')) tags.add('cache');
    if (flags.has('r') && r.os === 'bsd') tags.add('router');
    if (kind === 'connected' && (hostSized || (r.family === 4 && r.addr === '255.255.255.255'))) tags.add('bookkeeping');
    if (hostSized && loopNet) kind = 'self';
    if (r.family === 4 && hostSized && r.addr === '255.255.255.255') { tags.add('broadcast'); tags.add('bookkeeping'); }
    if (kind === 'neighbor' && r.os === 'bsd' && g.kind !== 'mac') tags.add('unresolved');
    if (kind === 'neighbor' && r.os !== 'bsd') tags.add('hostroute');
    if (kind === 'default' && r.os === 'bsd' && flags.has('I')) { tags.add('scoped'); tags.add('bookkeeping'); }
    r.kind = kind; r.tags = [...tags].sort(); r.flags_explained = explainFlags(r);
    r.cls = addrClass(r.netbits, r.family, r.plen); if (g.kind === 'mac') r.macFlags = macInfo(g.mac);
  }
  return routes;
}

function ifaceKey(name) {
  const m = /^([a-zA-Z\-]+)(\d*)/.exec(name); const base = m ? m[1] : name, num = m && m[2] ? Number(m[2]) : -1;
  let rank = 3;
  if (isLo(name)) rank = 9;
  else if (/^(en|eth|eno|ens|enp|em|wlan|wlp|wlo|wl|ap|bridge)/.test(name) || /^\d+\.\d+\.\d+\.\d+$/.test(name)) rank = 0;
  else if (/^(utun|tun|tap|wg|ppp|ipsec|gif|stf)/.test(name)) rank = 1;
  else if (/^(docker|br-|veth|vmnet|vboxnet|virbr)/.test(name)) rank = 2;
  return [rank, base, num, name];
}
function cmpKeys(a, b) { for (let i = 0; i < Math.max(a.length, b.length); i++) { const x = a[i], y = b[i]; if (x === undefined) return -1; if (y === undefined) return 1; if (x < y) return -1; if (x > y) return 1; } return 0; }

function buildGraph(routes, ifcfg, hostname, source) {
  const nodes = {};
  const add = (id, kw) => { let n = nodes[id]; if (!n) { n = Object.assign({ id, children: [], routes: [], tags: [], parent: null, sub: '', note: '' }, kw); nodes[id] = n; } return n; };
  const mergeTags = (n, r) => { for (const t of r.tags) if (!n.tags.includes(t)) n.tags.push(t); };
  add('host', { kind: 'host', label: hostname, family: 0, note: source });
  const good = routes.map((r, i) => [i, r]).filter(([, r]) => r.ok);
  for (const name of [...new Set(good.map(([, r]) => r.iface))].sort((a, b) => cmpKeys(ifaceKey(a), ifaceKey(b)))) {
    const n = add('if:' + name, { kind: 'iface', label: name, family: 0, parent: 'host', desc: ifaceKind(name), addrs: [] });
    const info = ifcfg[name]; if (info) { n.info = info; n.addrs = [...info.inet, ...info.inet6]; }
  }
  for (const [i, r] of good) {  // 1. connected prefixes, neighbors, own addresses
    let n;
    if (r.kind === 'connected') n = add(`net:${r.family}:${r.iface}:${r.cidr}`, { kind: 'net', label: r.cidr, family: r.family, parent: 'if:' + r.iface, addr: r.addr, plen: r.plen, bits: r.bits, abits: r.netbits });
    else if (r.kind === 'neighbor' || r.kind === 'self') {
      n = add(`${r.kind === 'neighbor' ? 'nb' : 'self'}:${r.family}:${r.iface}:${r.addr}`, { kind: r.kind, label: r.addr, family: r.family, addr: r.addr, plen: r.plen, bits: r.bits, abits: r.netbits });
      if (r.gw.kind === 'mac') { n.mac = r.gw.mac; n.macFlags = r.macFlags; } if (r.expire && r.expire !== '!' && r.expire !== '-') n.expire = r.expire; if (r.scope) n.scope = r.scope;
    } else continue;
    n.routes.push(i); r.node = n.id; mergeTags(n, r);
  }
  for (const [i, r] of good) {  // 2. remote prefixes hang under their next hop
    if (r.kind !== 'remote' && r.kind !== 'default') continue;
    const g = r.gw; let parent;
    if (g.kind === 'ip' && g.fam === r.family) {
      let gid = `nb:${r.family}:${r.iface}:${g.ip}`; if (nodes[`self:${r.family}:${r.iface}:${g.ip}`]) gid = `self:${r.family}:${r.iface}:${g.ip}`;
      const gw = add(gid, { kind: 'neighbor', label: g.ip, family: r.family, addr: g.ip, plen: FAMILY_MAX[r.family], bits: g.bits, abits: g.bits });
      if (!gw.tags.includes('router')) gw.tags.push('router');
      if (isLinkLocalBits(g.bits, r.family) && !gw.tags.includes('linklocal')) gw.tags.push('linklocal');
      parent = gw.id;
    } else parent = 'if:' + r.iface;
    const n = add(`rt:${r.family}:${r.iface}:${g.ip || g.raw}:${r.cidr}`, { kind: r.kind, label: r.cidr, family: r.family, parent, addr: r.addr, plen: r.plen, bits: r.bits, abits: r.netbits });
    n.routes.push(i); r.node = n.id; mergeTags(n, r);
  }
  const nets = Object.values(nodes).filter((n) => n.kind === 'net');
  for (const n of Object.values(nodes)) {  // 3. neighbors go under the most specific connected prefix on their interface
    if ((n.kind !== 'neighbor' && n.kind !== 'self') || n.parent) continue;
    const iface = n.id.split(':', 3)[2]; let best = null;
    for (const m of nets) { if (m.family !== n.family || m.parent !== 'if:' + iface || m.plen >= FAMILY_MAX[n.family]) continue; if (n.abits.startsWith(m.bits) && (!best || m.plen > best.plen)) best = m; }
    n.parent = best ? best.id : 'if:' + iface;
    if (best && n.family === 4 && n.abits === best.bits + '1'.repeat(32 - best.plen)) for (const t of ['broadcast', 'bookkeeping']) if (!n.tags.includes(t)) n.tags.push(t);
    if (n.kind === 'self') for (const m of nets) {
      const owner = m.parent.slice(3);
      if (m.family !== n.family || m.plen >= FAMILY_MAX[n.family] || isLo(owner) || nodes[m.parent].info || (n.scope && n.scope !== owner) || (isLinkLocalBits(n.abits, n.family) && !n.scope) || !n.abits.startsWith(m.bits)) continue;
      const ifn = nodes[m.parent]; if (!ifn.addrs.some((a) => a.split('/')[0] === n.addr)) ifn.addrs.push(n.addr + '/' + m.plen);
    }
  }
  const childKey = (c) => {
    const k = c.kind, ip = c.abits || '';
    if (k === 'iface') return [0, ...ifaceKey(c.label)];
    if (k === 'net') return [1, c.family, +c.tags.includes('bookkeeping'), +c.tags.includes('multicast'), c.plen, ip];
    if (k === 'neighbor' || k === 'self') return [2, c.family, +(k === 'self'), +!c.tags.includes('router'), +c.tags.includes('unresolved'), ip];
    return [3, c.family, c.plen, ip];
  };
  for (const n of Object.values(nodes)) if (n.parent) nodes[n.parent].children.push(n.id);
  for (const n of Object.values(nodes)) n.children.sort((a, b) => cmpKeys(childKey(nodes[a]), childKey(nodes[b])));
  for (const n of Object.values(nodes)) {
    if (n.abits) n.cls = addrClass(n.abits, n.family, n.kind === 'net' || n.kind === 'remote' || n.kind === 'default' ? n.plen : FAMILY_MAX[n.family]);
    if (n.kind === 'iface' && /^(utun|tun|tap|wg|ppp|ipsec|gif|stf)\d*$/.test(n.label)) {
      const real = n.addrs.some((a) => !a.startsWith('fe80:') && !a.startsWith('169.254.'));
      const busy = n.children.some((c) => !['linklocal', 'multicast', 'bookkeeping'].some((t) => nodes[c].tags.includes(t)));
      n.tunnelState = real || busy ? 'active' : 'idle';
    }
  }
  for (const n of Object.values(nodes)) describe(n, nodes, routes);
  return nodes;
}

function describe(n, _nodes, routes) {
  const k = n.kind, tags = n.tags, rs = n.routes.map((i) => routes[i]);
  const plural = (c, w) => `${c} ${w}${c === 1 ? '' : 's'}`;
  if (k === 'iface') {
    const bits = []; if (n.desc) bits.push(n.desc); const info = n.info || {};
    if (info.status) bits.push('status ' + info.status); if (info.ether) bits.push('MAC ' + info.ether);
    n.addrs.sort((a, b) => (a.includes(':') - b.includes(':')) || a.localeCompare(b));
    n.sub = n.addrs.length ? n.addrs[0] + (n.addrs.length > 1 ? ` +${n.addrs.length - 1}` : '') : '';
    if (n.tunnelState === 'idle') bits.push('idle tunnel: no real address, only link-local and scoped routes (on macOS: Continuity, iMessage/FaceTime signaling, iCloud Private Relay); ordinary traffic never uses it');
    if (n.tunnelState === 'active') bits.push('active tunnel: it has an address and real routes, so traffic is being carried through it (a VPN)');
    if (info.mtu && Number(info.mtu) < 1500 && n.tunnelState) bits.push(`MTU ${info.mtu}: 1500 minus the tunnel's own headers, so inner packets fit without fragmenting`);
    n.note = bits.join('; ');
  } else if (k === 'net') {
    let what = 'directly connected: hosts here are reached without a router';
    if (tags.includes('multicast')) what = 'multicast group range on this link';
    else if (tags.includes('linklocal')) what = 'link-local: valid only on this link, never routed';
    else if (tags.includes('loopback')) what = 'loopback network';
    else if (tags.includes('bookkeeping')) what = 'host-sized prefix the OS adds for its own bookkeeping';
    n.sub = n.children.length ? plural(n.children.length, 'neighbor') : ''; n.note = what;
  } else if (k === 'neighbor') {
    const parts = [];
    if (tags.includes('router')) parts.push('router (next hop)'); if (n.mac) parts.push(n.mac + (n.macFlags && n.macFlags.random ? ' (random)' : ''));
    if (tags.includes('unresolved')) parts.push('no MAC (ARP/NDP unresolved)'); else if (tags.includes('reject')) parts.push('unreachable');
    if (tags.includes('hostroute')) parts.push('host route');
    n.sub = parts.join(' · ');
    n.note = n.children.length ? `next hop for ${plural(n.children.length, 'route')}` : 'a host on this link (ARP/NDP cache entry)';
    if (n.expire) n.note += `; cache entry expires in ${n.expire}s`;
    if (tags.includes('unresolved')) n.note += '; the kernel asked for its MAC and got no answer (device asleep or gone); marked R so sends fail fast instead of asking again';
    if (n.macFlags && n.macFlags.random) n.note += '; the MAC has the locally-administered bit set: a randomized private Wi-Fi address, not the hardware one';
    if (n.macFlags && n.macFlags.multicast) n.note += '; multicast MAC (low bit of the first byte set)';
  } else if (k === 'self') {
    n.sub = 'this host'; n.note = "one of this host's own addresses; delivered locally via loopback";
    if (n.children.length) n.sub += ` · next hop for ${plural(n.children.length, 'route')}`;
  } else if (k === 'remote' || k === 'default') {
    if (k === 'default') { n.label = 'default'; n.sub = `everything else (${n.id.slice(n.id.lastIndexOf(':') + 1)})`; }
    else n.sub = 'via ' + (rs[0] && rs[0].gw.ip ? rs[0].gw.ip : 'the interface');
    n.note = 'forwarded to the next hop; the router decides the rest';
    if (tags.includes('static')) n.note += '; static (set by hand or DHCP)';
    if (tags.includes('scoped')) { n.sub += ' · scoped to ' + n.id.split(':')[2]; n.note = 'interface-scoped duplicate of the default route: used only by sockets bound to this interface'; }
  }
  if (tags.includes('broadcast') && (k === 'neighbor' || k === 'self')) { n.sub = 'broadcast address'; n.note = 'the all-hosts broadcast address of this prefix (or the link)'; }
  if (tags.includes('reject') && k !== 'neighbor') n.sub = (n.sub ? n.sub + ' · ' : '') + 'reject';
}


// ===================================================================== observations: what this table says, in English
function observations(M) {
  const N = M.nodes, R = M.routes, out = [];
  const note = (text, ids = [], level = 'info') => out.push({ text, ids: ids.filter(Boolean), level });
  const plural = (c, w) => `${c} ${w}${c === 1 ? '' : w.endsWith('s') ? 'es' : 's'}`;
  const cap = (t) => t.charAt(0).toUpperCase() + t.slice(1);
  const ifaces = Object.values(N).filter((n) => n.kind === 'iface');
  for (const ifn of ifaces) {
    if (isLo(ifn.label) || !ifn.addrs.length) continue;
    const v4 = ifn.addrs.filter((a) => !a.includes(':')), v6 = ifn.addrs.filter((a) => a.includes(':') && !a.startsWith('fe80:'));
    for (const a of v4) { const c = addrClass(v4bits(a.split('/')[0]), 4, 32); note(`${ifn.label} is ${a}, a ${c.label} address. ${cap(c.note)}.`, [ifn.id]); }
    if (v6.length) { const c = addrClass(v6bits(v6[0].split('/')[0]), 6, 128); note(`${ifn.label} also has ${plural(v6.length, 'IPv6 address')} such as ${v6[0]}, ${c.label}: ${c.note}.${v6.length > 1 ? ' With several, the OS picks a temporary one for outgoing connections and rotates it for privacy.' : ''}`, [ifn.id]); }
  }
  for (const fam of [4, 6]) {
    const famName = fam === 4 ? 'IPv4' : 'IPv6';
    const defs = R.filter((r) => r.ok && r.family === fam && r.kind === 'default' && !r.tags.includes('scoped'));
    if (!defs.length) { if (R.some((r) => r.ok && r.family === fam)) note(`No ${famName} default route: over ${famName} only the directly connected networks are reachable.`, [], 'warn'); continue; }
    const d = defs[0], n = N[d.node], gw = n && n.parent && N[n.parent].kind !== 'iface' ? N[n.parent] : null;
    let t = `Every ${famName} packet that matches nothing more specific goes to ${d.gw.ip || d.gateway} on ${d.iface}`, level = 'info';
    if (gw && gw.mac) t += `, whose MAC ${gw.mac} is in the cache${gw.expire ? ` (${gw.expire} s before it must be re-verified)` : ''}`;
    else if (gw && d.os === 'bsd') { t += ', which has NO resolved MAC: the router is unreachable right now'; level = 'warn'; }
    if (fam === 6 && d.gw.bits && isLinkLocalBits(d.gw.bits, 6)) t += '. A link-local next hop is normal for IPv6: routers advertise themselves with their fe80:: address';
    note(t + '.', [gw && gw.id, n && n.id], level);
    if (fam === 4 && /\.1$/.test(d.gw.ip)) note('The gateway sits on .1, the first usable address of its subnet. That is a vendor convention (Linksys and Netgear made 192.168.1.1 famous, Comcast gateways use 10.0.0.1), not a rule: it only has to be inside your subnet so you can ARP for it.', [gw && gw.id]);
    if (defs.length > 1) note(`${defs.length} ${famName} default routes (${defs.map((r) => r.iface).join(', ')}): on macOS the first in table order wins; Linux and Windows pick by metric.`, defs.map((r) => r.node), 'warn');
    if (/^(utun|tun|tap|wg|ppp|ipsec)/.test(d.iface)) note(`The ${famName} default route goes through ${d.iface}, a tunnel: a VPN is carrying all your ${famName} traffic.`, [n && n.id]);
  }
  const halves = R.filter((r) => r.ok && r.family === 4 && r.plen === 1);
  if (halves.length >= 2) note(`${halves.map((r) => r.cidr).join(' and ')} via ${halves[0].gw.ip || halves[0].gateway} on ${halves[0].iface}: the VPN trick. Two /1 routes cover the whole space and beat the real default by one bit, so every packet enters the tunnel while the original default stays in place underneath.`, halves.map((r) => r.node));
  for (const net of Object.values(N).filter((n) => n.kind === 'net' && !['multicast', 'loopback', 'bookkeeping'].some((t) => n.tags.includes(t)))) {
    const kids = net.children.map((id) => N[id]).filter((k) => k.kind === 'neighbor' && k.routes.length);
    if (!kids.length || (N[net.parent] && N[net.parent].tunnelState === 'idle')) continue;
    const resolved = kids.filter((k) => k.mac), incomplete = kids.filter((k) => k.tags.includes('unresolved'));
    if (kids.every((k) => k.tags.includes('hostroute'))) { note(`${plural(kids.length, 'host route')} on ${net.label} (${kids.map((k) => k.label).join(', ')}): single addresses pinned explicitly, by hand or by DHCP. This OS keeps its ARP cache elsewhere, so no neighbors appear here.`, kids.map((k) => k.id)); continue; }
    let t = `${plural(kids.length, 'host')} on ${net.label} ${kids.length === 1 ? 'is' : 'are'} in the ARP/NDP cache`;
    if (resolved.length) t += `: ${resolved.length} resolved (packets exchanged in the last ~20 minutes; nothing scans the subnet, entries appear only when someone talks)`;
    if (incomplete.length) t += `${resolved.length ? '; ' : ': '}${incomplete.length} incomplete (asked for a MAC, no answer: probably asleep or gone)`;
    note(t + '.', kids.map((k) => k.id));
    const rnd = resolved.filter((k) => k.macFlags && k.macFlags.random);
    if (rnd.length) note(`${rnd.length} of the ${plural(resolved.length, 'resolved MAC')} on ${net.label} ${rnd.length === 1 ? 'has' : 'have'} the locally-administered bit set: randomized private Wi-Fi addresses (phones and laptops rotate these per network), not burned-in ones.`, rnd.map((k) => k.id));
  }
  const mdns = R.find((r) => r.ok && r.addr === '224.0.0.251' && r.gw.mac);
  if (mdns) note(`224.0.0.251 with MAC ${mdns.gw.mac} is mDNS (Bonjour), how Apple devices find each other. Multicast MACs are never learned by ARP; they are computed from the IP.`, [mdns.node]);
  const idle = ifaces.filter((n) => n.tunnelState === 'idle');
  if (idle.length) note(`${plural(idle.length, 'tunnel interface')} (${idle.map((n) => n.label).join(', ')}) ${idle.length === 1 ? 'carries' : 'carry'} only link-local addresses and interface-scoped routes: idle system tunnels. On macOS these belong to Continuity, iMessage/FaceTime signaling and iCloud Private Relay; ordinary traffic never uses them. A connected VPN would show an address and real routes.`, idle.map((n) => n.id));
  if (M.os === 'linux') note('Linux keeps the ARP cache outside this table (`ip neigh`) and its own addresses in a separate local table (`ip route show table local`), so neighbors and self entries are absent here.');
  if (M.os === 'windows') note('Windows lists its own addresses and broadcast addresses as On-link /32 routes; the ARP cache is separate (`arp -a`).');
  return out;
}

// ===================================================================== diff: what changed between two tables
const routeKey = (r) => (r.ok ? `${r.family}|${r.cidr}${r.scope ? '%' + r.scope : ''}|${r.gateway}|${r.iface}` : `raw|${r.raw.trim()}`);
function diffRoutes(before, after) {
  const b = new Set(before.map(routeKey)), a = new Set(after.map(routeKey));
  return { added: after.filter((r) => !b.has(routeKey(r))), removed: before.filter((r) => !a.has(routeKey(r))) };
}
function diffObservations(diff, before, after) {
  const out = [], plural = (c, w) => `${c} ${w}${c === 1 ? '' : 's'}`;
  const beforeIf = new Set(before.map((r) => r.iface)), newIf = [...new Set(diff.added.map((r) => r.iface))].filter((i) => !beforeIf.has(i));
  if (newIf.length) out.push(`New interface${newIf.length === 1 ? '' : 's'} ${newIf.join(', ')} appeared with ${plural(diff.added.filter((r) => newIf.includes(r.iface)).length, 'route')}.`);
  const halves = diff.added.filter((r) => r.ok && r.plen === 1);
  if (halves.length >= 2) out.push(`${halves.map((r) => r.cidr).join(' + ')} via ${halves[0].gw.ip || halves[0].gateway} on ${halves[0].iface} were added: a VPN is now capturing all IPv4 traffic by out-specifying the default route by one bit.`);
  for (const r of diff.added.filter((r) => r.ok && r.kind === 'default' && !r.tags.includes('scoped'))) out.push(`A new default route via ${r.gw.ip || r.gateway} on ${r.iface}${/^(utun|tun|tap|wg|ppp)/.test(r.iface) ? ': a VPN took over as the way out' : ''}.`);
  for (const r of diff.removed.filter((r) => r.ok && r.kind === 'default' && !r.tags.includes('scoped'))) out.push(`The default route via ${r.gw.ip || r.gateway} on ${r.iface} is gone${after.some((x) => x.ok && x.kind === 'default' && !x.tags.includes('scoped')) ? '' : ': nothing off the local networks is reachable now'}.`);
  const nb = (list) => list.filter((r) => r.ok && r.kind === 'neighbor').length;
  if (nb(diff.added) || nb(diff.removed)) out.push(`ARP/NDP cache churn: ${nb(diff.added)} neighbor entries appeared, ${nb(diff.removed)} expired or vanished. That is normal; entries live about 20 minutes.`);
  if (!out.length) out.push(diff.added.length || diff.removed.length ? `${plural(diff.added.length, 'route')} added, ${plural(diff.removed.length, 'route')} removed, none of them structural.` : 'The two tables are identical.');
  return out;
}

function buildModel(text, ifcfgText, hostname) {
  const { routes, meta } = parseNetstat(text);
  classify(routes);
  const ifcfg = ifcfgText && ifcfgText.trim() ? parseIfconfig(ifcfgText) : {};
  const nodes = buildGraph(routes, ifcfg, hostname || 'this host', '');
  const M = { hostname: hostname || 'this host', os: meta.os, routes, nodes, glossary: flagGlossary(routes), generated: new Date().toLocaleString() };
  M.observations = observations(M);
  return M;
}
